version: '2'

services:
  db:
    container_name: template-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      APP_ENV: development
    depends_on:
      - db
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
